apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-metrics-server
spec:
  selector:
    matchLabels:
      app: argocd-metrics-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: argocd-metrics-server
    spec:
      containers:
        - image: bogdanadrianburciu/argocd-extension-metrics:v1.0.4-rc3
          imagePullPolicy: IfNotPresent
          args:
            - '-enableTLS=false'
            - '-skipPrometheusTLSVerify=true'
          name: argocd-metrics-server
          env:
            - name: PROMETHEUS_APIKEY
              valueFrom:
                secretKeyRef:
                  name: groundcover-api-key
                  key: datasource-api-key
          ports:
            - containerPort: 9003
              name: metrics
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: argocd-metrics-server-configmap
